[project]
name = "poetry-multiproject-plugin"
version = "2.0.0"
description = "A Poetry plugin that makes it possible to use relative package includes."
requires-python = ">=3.10"
authors = [{name = "David Vujic"}]
readme = "README.md"
keywords = ["poetry", "plugin", "packaging", "monorepo", "polylith", "workspace"]
license = "MIT"
dependencies = [
    "poetry",
    "tomlkit==0.*",
    "mypy",
]

[project.urls]
Homepage = "https://github.com/davidvujic/poetry-multiproject-plugin"
Repository = "https://github.com/davidvujic/poetry-multiproject-plugin"

[project.entry-points."poetry.application.plugin"]
poetry-multiproject-plugin = "poetry_multiproject_plugin:MultiProjectPlugin"

[dependency-groups]
dev = [
    "black==26.*",
    "isort==9.*",
    "flake8==7.*",
    "pytest==9.*",
]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
