version: '2.1'
orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            python --version
            poetry run flake8 ./poetry_multiproject_plugin
            poetry run mypy ./poetry_multiproject_plugin
            poetry run pytest -v
          name: Linting and Testing

workflows:
  main:
    jobs:
      - test
